// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wanoxeuutcbkrgzjejft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indhbm94ZXV1dGNia3JnemplamZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE2OTE0NjYsImV4cCI6MjA4NzI2NzQ2Nn0.Seh_dqvt3CpazUe1knpZtfTZbx_B0QbTNe-qfzcr4Dg";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);